### ISSUE TITLE
Hardcore mód

### ISSUE THREAD

**Issue by ProtXVIP** [S3nS3IW00/EnderCraft#15]
Legyen kreatív plot
Játékos nevem:ProtX

**Comment by S3nS3IW00** [comment]
A kreatív plot, nem hardcore mód rész :D De megfontoljuk ;)

**Comment by ProtXVIP** [comment]
Tudom csak a Címet elirtam
2017. szept. 12. 18:31 ezt írta ("S3nS3IW00" <notifications@github.com>):
