### ISSUE TITLE
Piac

### ISSUE THREAD

**Issue by IcyAlex** [S3nS3IW00/EnderCraft#17]
Lehetne minden játékosnak csinálni egy piacot ládából és egy táblából.
Így a játékosok máshogy is szerezhetnek pénzt.

Ui.: Nekem nem tetszik az aukciós módszer, csak azért írtam ezt.

**Comment by S3nS3IW00** [comment]
Ez régebben be volt iktatva, viszont az elavult plugin miatt. Lehet vissza kerűl, javítás után.
