### ISSUE TITLE
Sziasztok 

### ISSUE THREAD

**Issue by GamerGergoXD** [S3nS3IW00/EnderCraft#2]

**Comment by GamerGergoXD** [comment]
Sziasztok 
1.Arénaban nem jó néha a hidbox rá ütök az emberre és nem sebződik az ember ki kellenr javitani
2.a spawn-t fel kellene ujjitani és akkor a spawnon legyen még a sarkokba kis Dragon-ok 
3.nincsen sokszor mostmár Event nincs pénz szerzési lehetőség :)

**Comment by GamerGergoXD** [comment]
Oké köszönöm szépen a szerver 10/10 nekem nagyon jó ra értékelem ezt meg érdemlitek Gg broo

**Comment by S3nS3IW00** [comment]
Köszönjük.

**Comment by GamerGergoXD** [comment]
Ez semmiség csak természetes
