### ISSUE TITLE
Permission hiba

### ISSUE THREAD

**Issue by Fr3lly** [S3nS3IW00/EnderCraft#4]
Üdvözletem!
A szerveren ECTag rangnak, van /capslimit joga, ezálltál ő is betudja állítani hogy mennyi legyen a caps limit.
![img_20170821_153628](https://user-images.githubusercontent.com/26357505/29521623-8ce39d60-8686-11e7-8ade-2a0669fb772e.jpg)

**Comment by Fr3lly** [comment]
![img_20170821_154312](https://user-images.githubusercontent.com/26357505/29525385-c21586e0-8692-11e7-9053-b582d69b261c.jpg)

**Comment by S3nS3IW00** [comment]
Köszönjük! Jutalom: 100 kredit
